[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "c61e069f6376bb046a52a2edff1691f3c76b5b7c"
os = "macos"

    [[Objconv.download]]
    sha256 = "860e3273e9b782f983e5a62a2eec0ba112491f96605471db2d96a6839816631a"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.aarch64-apple-darwin.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "9c1282e0b7227b9f3895b414dddc5fe89b8eae0c"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "fe8ed6c47903b9584cc236375d50b415d269e157fea75ccdec2036f9206b8727"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.aarch64-linux-gnu.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "f7611ea3881a0612c8eb11ceab826519aa7d2831"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "8419f442e541b9d373d8393838dee971dfbf8e4f9ecb59a5e49f633443125835"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.aarch64-linux-musl.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "eaa5e3e3e5d707f7427757d074ac9548636ac833"
os = "freebsd"

    [[Objconv.download]]
    sha256 = "48daccb749e869526c2aecd2a85b9564f62b229027fbefb608482123248db704"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.aarch64-unknown-freebsd.tar.gz"
[[Objconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "05491acffc024ccb6a7b50a8cc00d3eb53c71497"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "c680404bf8b26dea791caca647327446797606a02436d3b603aea2dac37e3895"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.armv6l-linux-gnueabihf.tar.gz"
[[Objconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d5ef4bd0670cb99523af1d9d616905fc1ccc224e"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "299ff772aafc8f07a23205a1c7f8179b457189f05b74628027063e3736b4abf4"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.armv6l-linux-musleabihf.tar.gz"
[[Objconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1bc36d5d302332a9e80012614a51082a520db01d"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "ed51a94f71088ac0836709ad25758820b0ca5b36eb1671bb4f4594d1cc2e8efb"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.armv7l-linux-gnueabihf.tar.gz"
[[Objconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a83657b2376e782b99f33dd185d63d9d29167a3b"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "8e14ee4be9c69a3a59aa8629395ffb68bead8fbae7f7e4f929c116f75343367a"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.armv7l-linux-musleabihf.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "d83f54049e95db4390e64bad3ca5e3a5beb85cf3"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "c0b7d67cbdc062b9d98b6c0869f388dc921c1c3673fab2ba8a3984eaca62d131"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.i686-linux-gnu.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "36a3b98776d553bbea481d150e000b308e20c0f7"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "c76ae5c526b65a5b0877ae0992ef8da2c0397c3daa080cd952fdb8e9ee9d7dde"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.i686-linux-musl.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "03cc1ed1e6c9a4419d470561862899ba411c5c07"
os = "windows"

    [[Objconv.download]]
    sha256 = "a7951f7c146e93e46b87e8308332c2150d4abd5978ff7315dfb6b7750a868db6"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.i686-w64-mingw32.tar.gz"
[[Objconv]]
arch = "powerpc64le"
git-tree-sha1 = "8fd19a3d6a61b05901b13fd728d28b928372dca9"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "a7d9efa7c94e4c4d3d9f1713352f240c29ddfa4c2d22512d827c2d236d076004"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.powerpc64le-linux-gnu.tar.gz"
[[Objconv]]
arch = "riscv64"
git-tree-sha1 = "2b6536481c6ed7ce90b52d34e2258fd1480d54a6"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "48402ace7444f3e55b5f514cfc610d16da2de5c96f499e8e93345ae12494a23f"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.riscv64-linux-gnu.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "c5315aac02d3c7f689e90a4e7e080b3681caa2b8"
os = "macos"

    [[Objconv.download]]
    sha256 = "212a3c65bc1bbf84ecd3b0847974fb360c873dffe76882d1a475aa9d48ecc5dc"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.x86_64-apple-darwin.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "cc2d9cc248874b07e4e31bfe85fbe27214533856"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "4052e750035091da44c0de5ebe2760393ac980103701a1bd1a91d417be55568e"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.x86_64-linux-gnu.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "768cbc5a66b21eb035130b8b350e874693521d39"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "3bfc4be844d95de1a9b468488ed27ec2fb8a3b9fe15704b20d50933acd6db1e8"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.x86_64-linux-musl.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "854cf5fa1f639e13178918fa859548f191ec478c"
os = "freebsd"

    [[Objconv.download]]
    sha256 = "699eaf2450be4d073ff72056b5263fcfbe3ba3acade880414745ffb785f1025a"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.x86_64-unknown-freebsd.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "8b677fd6a32ba23245f1e78a9399d7d4d4bba496"
os = "windows"

    [[Objconv.download]]
    sha256 = "e6342af42c8e46416559876ec5dfa9a88aca27f1eed01802254a3dee0ef1b375"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.54.0+0/Objconv.v2.54.0.x86_64-w64-mingw32.tar.gz"
