[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "aa17a748302b539bb539230137873213f1465baa"
os = "macos"

    [[Objconv.download]]
    sha256 = "404606c0fad6f5b6f745e5d6e9ad83e82442cc891fac7cb00dd2e1fd5df5a918"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.aarch64-apple-darwin.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "928917ebdcd091fa721f98f4b09aa420cd077d7a"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "460258bbc050104ef59d897953d6c513e899f5bbdc3b22cc8d1bb406501a839d"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.aarch64-linux-gnu.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "5120ff9ad0d4287806a973d59ea9cdbe460f3dd8"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "3cfd23f05eb9abadb55044e3b4c6e66128cc2cbdb63e6578886b902e166eea20"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.aarch64-linux-musl.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "b5eab550ce3f00d65e98e9a514ee9ca0e667969f"
os = "freebsd"

    [[Objconv.download]]
    sha256 = "acaf878748f732189f7c7fc3f41473fd5428b21cfa51b3c97992f0d47b151732"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.aarch64-unknown-freebsd.tar.gz"
[[Objconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3597dc0f6834328e915086486f6954185f16d3c6"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "6b5e3fd1526517464811624bce271feb84b3b070360be1498feb0c426ec9958b"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.armv6l-linux-gnueabihf.tar.gz"
[[Objconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "84e3f6385dfabcc65328b1f00e6791ae1c2db10b"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "c7b7399794c384376739818ca89c1b633439b296f44f5ce5d2f843f3c206e68c"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.armv6l-linux-musleabihf.tar.gz"
[[Objconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f0b2d72d40546e56e6eb4653a8a2d9dc10c9ab9"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "c1db921f393442cc1702d38f17adafb1364dc569f8f9598f6d77530a276db00d"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.armv7l-linux-gnueabihf.tar.gz"
[[Objconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6dafd0dd650b96c683d8fe4b9cdc64fb80599af5"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "e3f2a8025a92902a7f66ae294817df3f1fe176f5bf5e022f3c470983ef41c2bd"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.armv7l-linux-musleabihf.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "bcc55772e920c59b45b529b05870225957bc448f"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "b84ff612a053c26fbdd52132dcaacae82076965c99ebba9534cc1da4da3cddd5"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.i686-linux-gnu.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "84a538eada2c77785646c132af2c7b14695bf00e"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "5c173abc6ddb572e462148b6220f774c9f9ccec70542c94051dafbc4a34e737f"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.i686-linux-musl.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "449df6440e351e2fb8f2756052bd3d8c8adacf2a"
os = "windows"

    [[Objconv.download]]
    sha256 = "d13e5d880ba769be971e2c5e3c229671c627a40eedfd42e23f1c2694ad8df4d8"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.i686-w64-mingw32.tar.gz"
[[Objconv]]
arch = "powerpc64le"
git-tree-sha1 = "fb2b2e97d42fc409ab9e383182650fa79bdf6b66"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "f29ed1e24c087693d9ed15b35bf25d7f8ca76cb13ed42471ba0704abddf49417"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.powerpc64le-linux-gnu.tar.gz"
[[Objconv]]
arch = "riscv64"
git-tree-sha1 = "94d0a78019ce0e32eb5515dea56568e2c64a6f80"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "8a302c06e3e3ce47141fda3460dae1e71973beee8153914a6845b60ff719b9c2"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.riscv64-linux-gnu.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "816d5b28318f175d7949774ddc1c09f2e8dbd70f"
os = "macos"

    [[Objconv.download]]
    sha256 = "4e164331c71b93c2218dd098ae939775cd274f05e113191f431664b455ae6878"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.x86_64-apple-darwin.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "f6a3d1c9cae5f80a79533df4a843affdc78547aa"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "40d6c93f6699e9b2e2a5e4f947502bc8b5360eeadc6399fba27a24ea391adfba"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.x86_64-linux-gnu.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "9b86f397f0787d42e5c11957ed4adc9d41b31f88"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "080d34f5863b895103c05688d5da097cad95dedb6bfccfac5526333f015c408b"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.x86_64-linux-musl.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "a3fff9e198085954430c3f1e94232710d631e0c9"
os = "freebsd"

    [[Objconv.download]]
    sha256 = "00ae4be990e171717466b992741eb819cb9f3b94c9cc16231d78f69d92b7d8ea"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.x86_64-unknown-freebsd.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "5be012e4395db123463206bd46f2084d39c9b804"
os = "windows"

    [[Objconv.download]]
    sha256 = "f5d7e3cde236ffe9bbacfea1b888ee8a6bd543a12e4ed394dd4d817ab1127bc0"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.55.0+0/Objconv.v2.55.0.x86_64-w64-mingw32.tar.gz"
