[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "314c90ba3fcf017ae3252e9e86abf8873b78046b"
os = "macos"

    [[Objconv.download]]
    sha256 = "34fb564d319756a5bd30afcc146f95c5c37c508b99d8d50394323cd3d410da95"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.aarch64-apple-darwin.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "a7ea2884a9af97ff18e7633efa5ff12848a82dcf"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "a256b32dd8a2ccf79aae3ca7d221e66958ce8cd8b2e822e25a732afa852ba7a8"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.aarch64-linux-gnu.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "03f1358c7ec3d04271b2622704d6ad9f3535bf20"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "b0adb0d1604a79f2fa25186d94128930329d9822c3fb35cb1ed0096beaa559e3"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.aarch64-linux-musl.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "0e6c108f0215b451cc52ad149d262a653149f05d"
os = "freebsd"

    [[Objconv.download]]
    sha256 = "68f77afae03293baede37ec4c0181132e91c61839917a802743917270387e745"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.aarch64-unknown-freebsd.tar.gz"
[[Objconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d34f259b48bbab57ec04ed2a4ead2a47da6bd2f"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "82896e96d7a3cd6d51bdb892bfb12507d85223c0411bd8248b4a4cf59a5d8b16"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.armv6l-linux-gnueabihf.tar.gz"
[[Objconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f819a3f7ea2eddc40dba5614e409bb0d676e0e6"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "8950c3afd2ea291833998d102bde36226dada4c326333d11d163d32d441563fe"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.armv6l-linux-musleabihf.tar.gz"
[[Objconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9bd27c904681bfbca9fb2cbb393859808e36b680"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "55ac807b9e7006ec8b90beb0a6f6043c405e5c9a99acf352ec0271d91725ea2e"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.armv7l-linux-gnueabihf.tar.gz"
[[Objconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c9942554c7e071682800034ea0144e39b9cbd5d1"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "1de05eb34e5dd3578c2f76e82450ea8a3854610eb6cf0fb072842291c8a71448"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.armv7l-linux-musleabihf.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "2fc55acfce26673511f27301b165f55dd61954fa"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "e5bdd902125b13c32decd4ef3e6236ec4112b4ace0000e35152c2dab9be870c9"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.i686-linux-gnu.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "3eea44317df213f76f17a1f9ccc3102251c51977"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "16e0e18bb390bffc7531ab223df67460117439c7f6489a069a9c7a53678b3b74"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.i686-linux-musl.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "7bef06d3ca4a72adbf0b9188090bf36fb71b1228"
os = "windows"

    [[Objconv.download]]
    sha256 = "42d5075885dd96acf920fed57983223ae6eb9cdcd2753355a60819914ae62257"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.i686-w64-mingw32.tar.gz"
[[Objconv]]
arch = "powerpc64le"
git-tree-sha1 = "96bb45af1ff6abcfa20b16d0600b2a1ec7c007d5"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "56194d9d929b288bf178942c0a2d5eb0e6a13912ae73270b400c27dfdf5eecd6"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.powerpc64le-linux-gnu.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "78935a264fe1ae82950ad3a0196db9479ccd95fc"
os = "macos"

    [[Objconv.download]]
    sha256 = "4cf181ed14e76ab65a2a9c41a1f2ae80f56dbe59acaec74352bc5307ce87c7b6"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.x86_64-apple-darwin.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "0debf2ebd6a9e6f9caed81cf9c6f601a24ec8a57"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "cb7467202a5c44b1734aa52995013b1ba7f51c888bb27c167d13503d1b7f510c"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.x86_64-linux-gnu.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "00340df87c956e267810f7ca915bfda68464d215"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "3505b4985fc3925e4b1a86d41345bf08a522aebc369081cd298c3f8084cafab1"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.x86_64-linux-musl.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "e2b173d81fe1437575430d85814647e758967dbd"
os = "freebsd"

    [[Objconv.download]]
    sha256 = "5c9c37a46d9fe926f3182f8e1e04b14d39c2df44ffde5050b790a695e8d86f26"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.x86_64-unknown-freebsd.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "edf2158b0844998d129c9a8a4d570fef6e2ee892"
os = "windows"

    [[Objconv.download]]
    sha256 = "916a8315abcea331008591d1b823f7bc5188d0e62ba18cf77991830cd73a68f3"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.53.0+1/Objconv.v2.53.0.x86_64-w64-mingw32.tar.gz"
