[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "72c20a687e9bc92168981f81df6308022c9a19fd"
os = "macos"

    [[Objconv.download]]
    sha256 = "ff11284d7d8a2fbfca079bab3a71a6200c8e5b19571141e76b8a40ebbe67f679"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.aarch64-apple-darwin.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "2f6fa7ea8ad8be9bc82455a329d985c295cc083b"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "3f9e7c1a97932024ece4e6d9e619748e2f2e519e95e27d90fe75c9376adb3051"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.aarch64-linux-gnu.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "daaa6c27be8bfc01939441e528404c3fdef48f31"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "19324e6b73b28105132ee443473b1694e0c752ba06620d6c2f720488c578dba9"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.aarch64-linux-musl.tar.gz"
[[Objconv]]
arch = "aarch64"
git-tree-sha1 = "db4ba58d703059e94aac6d25d89c60bf23ed21f9"
os = "freebsd"

    [[Objconv.download]]
    sha256 = "5041b7e9a89d76e4c509612288f8783bfee091ca7ddf5413a8fdd533da36df31"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.aarch64-unknown-freebsd.tar.gz"
[[Objconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "010fe3944b493d671d80927d1d305f3475f43f27"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "70ff380937e5192483d65663527c0256a8201fa27c3a1c429554a0cbbd8f1a4d"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.armv6l-linux-gnueabihf.tar.gz"
[[Objconv]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4c469ce8aa7b24f1d0b651c2fec0cd559f39fabf"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "8e961196759aa58c16c380e5aa4b9bb14029c6e8594c06f75f177c7062437c7b"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.armv6l-linux-musleabihf.tar.gz"
[[Objconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e71c6591a972200d67c2109f773cc509d68f4ada"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "ef5337ed7a808b674a214c532fb1f045d3e7d4704c0e3749e649aee7e2f4e20c"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.armv7l-linux-gnueabihf.tar.gz"
[[Objconv]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e89143d44c81033928273c53ee421d9fd7f690b1"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "4764f1144533acad8ee41024a18d535063a034b7ee741150386eb95f3aee7786"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.armv7l-linux-musleabihf.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "b7ec43c99974471b684454638b5271e6c7cb2535"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "8391c6f59b0fa43a950c036119abf0ecf7f8313aac60ef4f19c957910b67b5f6"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.i686-linux-gnu.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "3500ab9f8d44231f7ce40d323425b1479b4a5f60"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "df84eed840943cdc5957816e823abc3ff82e833f10fd422a20ae8099906a13ff"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.i686-linux-musl.tar.gz"
[[Objconv]]
arch = "i686"
git-tree-sha1 = "8cf995b19fbd721554864fbcecee5af14afda998"
os = "windows"

    [[Objconv.download]]
    sha256 = "dcc78bc570bfee37af7f73ab15a5ec29b16820f93527afc1a31bee6f1d29bedd"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.i686-w64-mingw32.tar.gz"
[[Objconv]]
arch = "powerpc64le"
git-tree-sha1 = "806534ac6df40775ac66d77165c0a33d0c63e6de"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "13770dcf60d9e56ae7afccae262a90d71e0574d61b59f777350423093b6e29a5"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.powerpc64le-linux-gnu.tar.gz"
[[Objconv]]
arch = "riscv64"
git-tree-sha1 = "f5ee6bb345c7c738c673b8a0dfe8ef4a4000584f"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "e1bf1db61dff3c5f5f40f882d41135e78da8e15aee926885b67c9d13531bcb59"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.riscv64-linux-gnu.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "deb1c2ee2054e3f062bf1931f0ff63a07b83d9f3"
os = "macos"

    [[Objconv.download]]
    sha256 = "f054f966a8b26c6eab12725bd9ffe9edb3a2ed8ae58d6496533bbd50a8a55121"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.x86_64-apple-darwin.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "624ff519443a4d43b11c32692a15d1e8d2a14b64"
libc = "glibc"
os = "linux"

    [[Objconv.download]]
    sha256 = "291694e6b828250f7f1a52886272897aed939cc58fe0c6df98aff0bae78e7c0f"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.x86_64-linux-gnu.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "5112a0f7b8ff501d01c7ddab3742f191dc2d3f47"
libc = "musl"
os = "linux"

    [[Objconv.download]]
    sha256 = "790af2b270b01894ea841282fe8dc5c6e1affed9e0538b1e2d4e3158644031b0"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.x86_64-linux-musl.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "3e9fc9002f0d85fddf2c33ad13ef2c8a96fabc91"
os = "freebsd"

    [[Objconv.download]]
    sha256 = "e80b320285615d32f41fbcab0654687d734612da8e7e87608266c5ab78ffa064"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.x86_64-unknown-freebsd.tar.gz"
[[Objconv]]
arch = "x86_64"
git-tree-sha1 = "db42f8b7aa35f4ea5e8579ac6ac1ee2a939a89b7"
os = "windows"

    [[Objconv.download]]
    sha256 = "13b7714a3e20f2d6440ace76297b9e440ff51583a8491453db917924831a4fff"
    url = "https://github.com/JuliaBinaryWrappers/Objconv_jll.jl/releases/download/Objconv-v2.56.0+0/Objconv.v2.56.0.x86_64-w64-mingw32.tar.gz"
